### ISSUE TITLE
Auto-Run Functionality?

### ISSUE THREAD

**Issue by vbhayden** [yetanalytics/xapipe#91]
Hey there,

For the LRS Pipe project, is there any way of having it run a job by default on startup?  Sort of how the `init.d` folder works for something like Postgres' image etc.

The docs mentioned starting jobs with either the cli or json files, but I couldn't find anything for having it run jobs on startup with a specified storage method etc.

If not, then np and I'll work something out on our end.

Thanks,
-Trey

**Comment by cliffcaseyyet** [comment]
Hey Trey,

Yeah there are some options. First question are you running this in docker or natively?

**Comment by vbhayden** [comment]
Just Docker, my conscious forbids me from running anything natively.

**Comment by cliffcaseyyet** [comment]
Hahaha fair enough. Okay so my recommendation would be to take the base container and rewrap it with additional run commands/CLI args. In this way you can plop a preconfigured JSON config into the container itself, then when THAT resulting container starts up it will have a job preconfigured. You will need to change the CMD part of your customized container to point to the json file and also import the file itself via ADD.

It will look something along the lines of this (though you may have to play with it for your specific case):

```
FROM yetanalytics/xapipe:latest

# custom configuration
ADD my_job.json                /xapipe/jobs/my_job.json

WORKDIR /xapipe
ENTRYPOINT ["/xapipe/bin/run.sh", "--json /xapipe/jobs/my_job.json"]
```

**Comment by vbhayden** [comment]
Oh ok great, looks like we weren't too far off.

Thanks Cliff!
